apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: example-mq
spec:
  serviceName: example-mq
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example-mq
        tool: rabbitmq
    spec:
      containers:
      - name: example-mq
        image: lcantelli/kubernetes-rabbitmq-autocluster
        ports:
          - containerPort: 5672
            name: port-5672
          - containerPort: 4369
            name: port-4369
          - containerPort: 5671
            name: port-5671
          - containerPort: 15672
            name: port-15672
          - containerPort: 25672
            name: port-25672
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: example-mq
        env:
        - name: HOSTNAME
          valueFrom:
           fieldRef:
            fieldPath: status.podIP
        - name: AUTOCLUSTER_LOG_LEVEL
          value: "info"
        - name: AUTOCLUSTER_CLEANUP
          value: "true"
        - name: CLEANUP_INTERVAL
          value: "60"
        - name: CLEANUP_WARN_ONLY
          value: "false"
        - name: RABBITMQ_ERLANG_COOKIE
          value: "example-mq"
        - name: K8S_SERVICE_NAME
          value: "example-mq"
        - name: RABBITMQ_NODENAME
          value: "example-mq@$(HOSTNAME)"
  volumeClaimTemplates:
   - metadata:
       name: example-mq
     spec:
       accessModes: ["ReadWriteOnce"]
       resources:
         requests:
           storage: 1Gi
